// import "./globals.css";
import { Providers } from '@/redux/provider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <p>왜 되지</p>
      <Providers>{children}</Providers>
    </>
  )
}
